"""Contract tests for the Wave-2 engine verb: `groundwork honesty scan`.

The scan is the COMPUTABLE half of the milestone honesty audit — it diffs HEAD
against the sealed baseline (`bet/<slug>/approved`) for what git + grep can
establish without judgment: deleted or thinned test guards, hand-edits inside
generated files, and best-effort zero-caller exports. Its findings are leads
for the audit agent, never verdicts. Load-bearing behaviors:

  * exit 1 on any lead, exit 0 clean — CI-safe like `findings check`; and
  * exit 2 when the scan CANNOT run (no approved tag, not a git repo) —
    cannot-run must never masquerade as clean.

Run via `./dev test cli` (or pytest tests/cli/ from the scaffolds venv).
"""

import json
import os
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.resolve()
CLI = REPO_ROOT / "bin" / "groundwork.js"


def gw(args, cwd, *, check_returncode=None):
    proc = subprocess.run(
        ["node", str(CLI), *args],
        cwd=cwd, capture_output=True, text=True,
        env={"GROUNDWORK_NO_UPDATE_CHECK": "1", "PATH": os.environ["PATH"]},
    )
    if check_returncode is not None:
        assert proc.returncode == check_returncode, f"args={args}\nstdout={proc.stdout}\nstderr={proc.stderr}"
    return proc


def git(cwd, *args):
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", *args],
        cwd=cwd, check=True, capture_output=True, text=True,
    )


def commit_all(cwd, msg):
    git(cwd, "add", "-A")
    git(cwd, "commit", "-m", msg)


def seal_bet(tmp_path):
    """A minimal sealed bet: guards, a generated file, a referenced export — tagged approved."""
    guards = tmp_path / "tests" / "bets" / "b"
    guards.mkdir(parents=True)
    (guards / "test_slice_1_svc_thing.py").write_text(
        "def test_one():\n    assert True\n\ndef test_two():\n    assert True\n"
    )
    (guards / "test_slice_2_svc_other.py").write_text("def test_other():\n    assert True\n")
    src = tmp_path / "src"
    (src / "gen").mkdir(parents=True)
    (src / "gen" / "schema.js").write_text("// Code generated by gen-tool. DO NOT EDIT.\nconst shape = 1;\n")
    (src / "app.js").write_text("export function realThing() { return 1; }\n")
    (src / "main.js").write_text("import { realThing } from './app.js';\nrealThing();\n")
    git(tmp_path, "init", "-q")
    commit_all(tmp_path, "seal")
    git(tmp_path, "tag", "bet/b/approved")
    return tmp_path


def scan(cwd, *extra, check_returncode=None):
    return gw(["honesty", "scan", "--bet", "b", *extra], cwd, check_returncode=check_returncode)


def scan_json(cwd):
    proc = scan(cwd, "--json")
    return proc, json.loads(proc.stdout)


# ─── cannot-run: exit 2, never a fake clean ──────────────────────────────────

def test_no_git_repo_exits_2(tmp_path):
    assert scan(tmp_path).returncode == 2


def test_no_approved_tag_exits_2(tmp_path):
    git(tmp_path, "init", "-q")
    (tmp_path / "x.txt").write_text("x\n")
    commit_all(tmp_path, "init")
    proc = scan(tmp_path)
    assert proc.returncode == 2
    assert "bet/b/approved" in proc.stderr


def test_bet_flag_required(tmp_path):
    assert gw(["honesty", "scan"], tmp_path).returncode == 1
    assert gw(["honesty", "wat", "--bet", "b"], tmp_path).returncode == 1


# ─── clean repo: exit 0 ──────────────────────────────────────────────────────

def test_clean_repo_exits_0(tmp_path):
    seal_bet(tmp_path)
    scan(tmp_path, check_returncode=0)
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 0
    assert payload == {"clean": True, "findings": []}


# ─── deleted guards ──────────────────────────────────────────────────────────

def test_deleted_guard_file_is_a_lead(tmp_path):
    seal_bet(tmp_path)
    (tmp_path / "tests" / "bets" / "b" / "test_slice_2_svc_other.py").unlink()
    commit_all(tmp_path, "drop guard")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1 and payload["clean"] is False
    (f,) = [x for x in payload["findings"] if x["check"] == "deleted-guard"]
    assert f["file"] == "tests/bets/b/test_slice_2_svc_other.py"
    assert "deleted" in f["detail"]


def test_reduced_test_function_count_is_a_lead(tmp_path):
    seal_bet(tmp_path)
    # Two `def test_` at the tag, one at HEAD — the guard thinned without deletion.
    (tmp_path / "tests" / "bets" / "b" / "test_slice_1_svc_thing.py").write_text(
        "def test_one():\n    assert True\n"
    )
    commit_all(tmp_path, "thin guard")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1
    (f,) = [x for x in payload["findings"] if x["check"] == "deleted-guard"]
    assert f["file"] == "tests/bets/b/test_slice_1_svc_thing.py"
    assert "2 → 1" in f["detail"] and "heuristic" in f["detail"]


# ─── generated-file edits ────────────────────────────────────────────────────

def test_hand_edit_in_generated_file_is_a_lead(tmp_path):
    seal_bet(tmp_path)
    gen = tmp_path / "src" / "gen" / "schema.js"
    gen.write_text(gen.read_text() + "const sneaky = 2;\n")
    commit_all(tmp_path, "hand edit")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1
    (f,) = [x for x in payload["findings"] if x["check"] == "generated-edit"]
    assert f["file"] == "src/gen/schema.js"
    assert "generated" in f["detail"]


# ─── zero-caller shims (best-effort) ─────────────────────────────────────────

def test_unreferenced_export_is_a_best_effort_lead(tmp_path):
    seal_bet(tmp_path)
    (tmp_path / "src" / "orphan.js").write_text("export function orphanHelper() { return 1; }\n")
    commit_all(tmp_path, "add orphan")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1
    (f,) = [x for x in payload["findings"] if x["check"] == "zero-caller"]
    assert f["file"] == "src/orphan.js" and f["symbol"] == "orphanHelper"
    assert f["detail"].startswith("[best-effort]")
    # The referenced export from the sealed baseline never fires.
    assert not [x for x in payload["findings"] if x.get("symbol") == "realThing"]


def test_referenced_export_is_not_a_lead(tmp_path):
    seal_bet(tmp_path)
    (tmp_path / "src" / "used.js").write_text("export function usedHelper() { return 1; }\n")
    (tmp_path / "src" / "main.js").write_text(
        "import { realThing } from './app.js';\nimport { usedHelper } from './used.js';\nrealThing();\nusedHelper();\n"
    )
    commit_all(tmp_path, "add used helper")
    scan(tmp_path, check_returncode=0)


# ─── commented-proof (milestone stub read at HEAD, not diffed against the tag) ─
# The stub is materialized after the tag is cut (Delivery Step 0.5), so a stub
# born hollow never shows up in a tag diff — this check reads tests/bets/<slug>/
# test_milestone_*.<ext> at HEAD directly, every run.

def write_milestone_file(tmp_path, name, body):
    (tmp_path / "tests" / "bets" / "b" / name).write_text(body)


def test_commented_out_interface_test_is_a_lead(tmp_path):
    seal_bet(tmp_path)
    write_milestone_file(
        tmp_path,
        "test_milestone_1_thing.py",
        "import pytest\n\n\n"
        "# def test_milestone_1_thing_interface(cluster):\n"
        '#     """Assert what the user observes."""\n'
        '#     pytest.fail("bet-progress test not yet implemented — interface")\n\n\n'
        "@pytest.mark.asyncio\n"
        "async def test_milestone_1_thing_api(cluster, api_client):\n"
        '    """Assert the API outcome."""\n'
        '    pytest.fail("bet-progress test not yet implemented — api")\n',
    )
    commit_all(tmp_path, "materialize milestone stub, interface commented out")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1 and payload["clean"] is False
    (f,) = [x for x in payload["findings"] if x["check"] == "commented-proof"]
    assert f["file"] == "tests/bets/b/test_milestone_1_thing.py"
    assert "interface proof is commented out" in f["detail"]
    assert "less than what was approved" in f["detail"]


def test_active_interface_test_is_not_a_lead(tmp_path):
    seal_bet(tmp_path)
    write_milestone_file(
        tmp_path,
        "test_milestone_1_thing.py",
        "import pytest\n\n\n"
        "def test_milestone_1_thing_interface(cluster):\n"
        '    """Assert what the user observes."""\n'
        '    pytest.fail("bet-progress test not yet implemented — interface")\n\n\n'
        "@pytest.mark.asyncio\n"
        "async def test_milestone_1_thing_api(cluster, api_client):\n"
        '    """Assert the API outcome."""\n'
        '    pytest.fail("bet-progress test not yet implemented — api")\n',
    )
    commit_all(tmp_path, "materialize milestone stub, both layers active")
    scan(tmp_path, check_returncode=0)


def test_zero_declaration_milestone_file_is_a_lead(tmp_path):
    seal_bet(tmp_path)
    write_milestone_file(
        tmp_path,
        "test_milestone_1_thing.py",
        '"""Bet-progress test — Milestone 1: thing (both layers stripped)."""\n\nimport pytest\n',
    )
    commit_all(tmp_path, "materialize milestone stub, no declarations left")
    proc, payload = scan_json(tmp_path)
    assert proc.returncode == 1
    (f,) = [x for x in payload["findings"] if x["check"] == "commented-proof"]
    assert f["file"] == "tests/bets/b/test_milestone_1_thing.py"
    assert "no active test declaration" in f["detail"]


def test_non_milestone_test_file_is_never_scanned_for_commented_proof(tmp_path):
    """Only test_milestone_*.<ext> is in scope — a slice stub commented out the
    same way is a different proof surface and stays out of this check."""
    seal_bet(tmp_path)
    write_milestone_file(
        tmp_path,
        "test_slice_3_svc_other.py",
        "import pytest\n\n\n# def test_slice_3_other_interface(cluster):\n#     pytest.fail('x')\n",
    )
    commit_all(tmp_path, "add commented-out slice stub")
    scan(tmp_path, check_returncode=0)


# ─── output contract ─────────────────────────────────────────────────────────

def test_json_shape_and_human_footer(tmp_path):
    seal_bet(tmp_path)
    (tmp_path / "tests" / "bets" / "b" / "test_slice_2_svc_other.py").unlink()
    commit_all(tmp_path, "drop guard")
    _, payload = scan_json(tmp_path)
    assert set(payload) == {"clean", "findings"}
    for f in payload["findings"]:
        assert {"check", "file", "detail"} <= set(f)
    human = scan(tmp_path)
    assert human.returncode == 1
    # Leads, not verdicts — the footer routes real ones to the findings ledger.
    assert "leads" in human.stderr and "findings add" in human.stderr
