'use strict';

// The COMPUTABLE half of the milestone honesty audit: everything about a
// hollowed proof that git + grep can establish without judgment, run against
// the diff since the bet's sealed baseline (`bet/<slug>/approved`). Three
// checks, each honest about its own limits:
//
//   * deleted guards — bet-progress test files under tests/bets/<slug>/ deleted
//     or renamed away since the tag (git, solid), plus files whose test-function
//     count dropped (an occurrence-count heuristic, labelled as such);
//   * generated-file edits — changed files whose HEAD content carries a
//     generated marker (git + marker, solid);
//   * zero-caller shims — exported/public symbols in changed source files with
//     no reference anywhere else in the tree (a word-grep heuristic, capped and
//     labelled `[best-effort]`; unrecognized languages are skipped silently).
//
// Every finding is a LEAD for the honesty-audit agent, never a verdict — the
// agent judges what the scan can't (intent, mirrors requiring semantics,
// cross-slice erosion). Dependency-free: Node built-ins + git. The git
// plumbing is shared with `wiring scan` via ./git.js.

const fs = require('fs');
const path = require('path');
const {
  ScanUnavailableError, approvedTag, gitLines, showAt, ensureScannable,
  isTestFile, escapeRegExp,
} = require('./git');

const BEST_EFFORT_CAP = 20;
const MAX_FILE_BYTES = 512 * 1024;

// Generated-file markers, checked case-insensitively against HEAD content.
const GENERATED_MARKERS = [
  ['@generated', /@generated/i],
  ['DO NOT EDIT', /do not edit/i],
  ['Code generated by', /code generated by/i],
];

// Test-function shapes across the stacks GroundWork scaffolds. An occurrence
// count over these is a HEURISTIC (a renamed helper or a commented-out line
// moves it) — finding text says so.
const TEST_FN_PATTERNS = [/\bdef test_/g, /\bit\(/g, /\btest\(/g, /\bfunc Test/g];

const SOURCE_LANG = {
  '.js': 'js', '.mjs': 'js', '.cjs': 'js', '.jsx': 'js', '.ts': 'js', '.tsx': 'js',
  '.py': 'py',
  '.go': 'go',
};

// Cheap per-language exported-symbol extraction. Deliberately shallow — this
// feeds a best-effort grep, not a compiler. Unrecognized languages return [].
const SYMBOL_PATTERNS = {
  js: /^export\s+(?:default\s+)?(?:async\s+)?(?:function\*?|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm,
  py: /^(?:def|class)\s+([A-Za-z]\w*)/gm, // column 0 = top-level; `_`-prefixed excluded by the letter start
  go: /^func\s+([A-Z]\w*)/gm, // capitalized top-level funcs; methods don't match, on purpose
};

function countMatches(content, regex) {
  regex.lastIndex = 0;
  let n = 0;
  while (regex.exec(content) !== null) n++;
  return n;
}

function countTestFns(content) {
  return TEST_FN_PATTERNS.reduce((sum, re) => sum + countMatches(content, re), 0);
}

// ─── Check 1: deleted guards (git, solid; the count drop is a heuristic) ────

function deletedGuards(cwd, slug, tag) {
  const guardDir = `tests/bets/${slug}/`;
  const findings = [];

  // Files present at the tag but deleted or renamed away at HEAD.
  for (const line of gitLines(cwd, ['diff', '--diff-filter=DR', '--name-status', '-M', tag, 'HEAD', '--', guardDir])) {
    const parts = line.split('\t');
    const status = parts[0];
    if (status === 'D') {
      findings.push({
        check: 'deleted-guard',
        file: parts[1],
        detail: 'test file deleted since the approved tag — a guard the milestone sealed with is gone',
      });
    } else if (status.startsWith('R')) {
      const [from, to] = [parts[1], parts[2]];
      // A rename WITHIN the guard directory keeps the guard; only a move out
      // of tests/bets/<slug>/ takes it off the bet's proof surface.
      if (to && !to.startsWith(guardDir)) {
        findings.push({
          check: 'deleted-guard',
          file: from,
          detail: `test file renamed away from the bet's guard directory since the approved tag (now ${to})`,
        });
      }
    }
  }

  // Surviving files whose test-function count dropped. Occurrence-count
  // heuristic — it can miss a gutted body and misfire on a refactor.
  const atTag = gitLines(cwd, ['ls-tree', '-r', '--name-only', tag, '--', guardDir]);
  const atHead = new Set(gitLines(cwd, ['ls-tree', '-r', '--name-only', 'HEAD', '--', guardDir]));
  for (const file of atTag) {
    if (!atHead.has(file)) continue; // deletion already reported above
    const before = showAt(cwd, tag, file);
    const after = showAt(cwd, 'HEAD', file);
    if (before === null || after === null) continue;
    const a = countTestFns(before);
    const b = countTestFns(after);
    if (b < a) {
      findings.push({
        check: 'deleted-guard',
        file,
        detail: `test-function count dropped ${a} → ${b} since the approved tag (occurrence-count heuristic over def test_/it(/test(/func Test)`,
      });
    }
  }

  return findings;
}

// ─── Check 2: generated-file edits (git + marker, solid) ────────────────────

function generatedEdits(cwd, tag) {
  const findings = [];
  for (const file of gitLines(cwd, ['diff', '--diff-filter=M', '--name-only', tag, 'HEAD'])) {
    if (file.startsWith('.groundwork/')) continue;
    const content = showAt(cwd, 'HEAD', file);
    if (content === null) continue;
    const marker = GENERATED_MARKERS.find(([, re]) => re.test(content));
    if (marker) {
      findings.push({
        check: 'generated-edit',
        file,
        detail: `changed since the approved tag but carries a generated-file marker ("${marker[0]}") — a hand-edit inside a generated file drifts from its generator`,
      });
    }
  }
  return findings;
}

// ─── Check 3: zero-caller shims (best-effort, capped) ───────────────────────

function extractSymbols(lang, content) {
  const re = SYMBOL_PATTERNS[lang];
  if (!re) return [];
  re.lastIndex = 0;
  const names = new Set();
  let m;
  while ((m = re.exec(content)) !== null) names.add(m[1]);
  return [...names];
}

function zeroCallerShims(cwd, tag) {
  // Candidate files: source files changed since the tag, excluding tests and
  // .groundwork/. Unrecognized languages skip silently — never fake precision.
  const candidates = gitLines(cwd, ['diff', '--diff-filter=ACMR', '--name-only', tag, 'HEAD']).filter((f) => {
    if (f.startsWith('.groundwork/')) return false;
    if (isTestFile(f)) return false;
    return !!SOURCE_LANG[path.extname(f)];
  });
  if (!candidates.length) return [];

  // Reference corpus: every tracked, non-test source file, read once. Working
  // tree content (== HEAD after committed slices); oversized files skipped.
  const corpus = [];
  for (const f of gitLines(cwd, ['ls-files'])) {
    if (!SOURCE_LANG[path.extname(f)] || f.startsWith('.groundwork/') || isTestFile(f)) continue;
    try {
      const full = path.join(cwd, f);
      if (fs.statSync(full).size > MAX_FILE_BYTES) continue;
      corpus.push({ file: f, content: fs.readFileSync(full, 'utf8') });
    } catch { /* unreadable → skip */ }
  }

  const findings = [];
  for (const file of candidates) {
    if (findings.length >= BEST_EFFORT_CAP) break;
    const content = showAt(cwd, 'HEAD', file);
    if (content === null) continue;
    for (const symbol of extractSymbols(SOURCE_LANG[path.extname(file)], content)) {
      if (findings.length >= BEST_EFFORT_CAP) break;
      const word = new RegExp(`\\b${escapeRegExp(symbol)}\\b`);
      const referenced = corpus.some((c) => c.file !== file && word.test(c.content));
      if (!referenced) {
        findings.push({
          check: 'zero-caller',
          file,
          symbol,
          detail: `[best-effort] exported symbol '${symbol}' has no reference outside its defining file (word-grep over tracked non-test sources) — a shim nothing in the shipping build reaches?`,
        });
      }
    }
  }
  return findings;
}

// ─── Entry point ────────────────────────────────────────────────────────────

function scan(targetDir, slug) {
  const tag = ensureScannable(targetDir, slug);

  const findings = [
    ...deletedGuards(targetDir, slug, tag),
    ...generatedEdits(targetDir, tag),
    ...zeroCallerShims(targetDir, tag),
  ];
  return { clean: findings.length === 0, findings };
}

module.exports = {
  ScanUnavailableError,
  approvedTag,
  scan,
};
