#!/usr/bin/env node
'use strict';

// GENERATED by the GroundWork docs-site generator — do not hand-edit. Regenerated
// verbatim on `npx groundwork-method update` (Family: docs-site — regenerate with
// recorded options).
//
// review-throughput plan, Wave 3a, slice C2b — replaces the plain `next dev` as
// the `dev` script. Runs the live-bets watcher (sync-live-bets.js --watch, C2a)
// alongside the Next dev server, inherited stdio, so `pnpm dev` keeps the docsite
// live for the whole session instead of going stale at boot. `predev` still runs
// a one-shot sync first (package.json, unchanged) so the very first render is
// fresh even before the watcher's first tick.
//
// One process exiting stops the other — Ctrl-C (or either child dying on its
// own) tears the whole thing down instead of leaving an orphaned watcher.
//
// Dependency-free: Node built-ins only (child_process). `next` is resolved via
// the inherited PATH: this script is itself launched as the `dev` npm/pnpm
// script, and both package managers prepend node_modules/.bin to PATH for
// script children — the same resolution `"dev": "next dev"` relied on before.

const { spawn } = require('child_process');

const children = [];
let exiting = false;

function spawnChild(command, args) {
  const child = spawn(command, args, {
    stdio: 'inherit',
    // Windows needs a shell to resolve npm-installed .cmd shims; POSIX resolves
    // `next`/`node` off the inherited PATH directly.
    shell: process.platform === 'win32',
  });
  children.push(child);
  return child;
}

function stopAll() {
  for (const child of children) {
    if (!child.killed) {
      try {
        child.kill();
      } catch {
        // already gone
      }
    }
  }
}

function shutdown(code) {
  if (exiting) return;
  exiting = true;
  stopAll();
  process.exit(code == null ? 0 : code);
}

const watcher = spawnChild('node', ['scripts/sync-live-bets.js', '--watch']);
const next = spawnChild('next', ['dev']);

watcher.on('exit', (code) => {
  if (exiting) return;
  console.log('[dev] sync-live-bets watcher exited — stopping next dev');
  shutdown(code);
});

next.on('exit', (code) => {
  if (exiting) return;
  console.log('[dev] next dev exited — stopping the live-bets watcher');
  shutdown(code);
});

process.on('SIGINT', () => shutdown(0));
process.on('SIGTERM', () => shutdown(0));
