import {
  formatFiles,
  generateFiles,
  Tree,
  names,
} from '@nx/devkit';
import * as path from 'path';
import { recordGeneratorProvenance } from '../shared/provenance';
import {
  promoteEngineerSkill,
  deployStackDocs,
  ensureOptionalInfra,
  readProjectPrefix,
} from '../shared/scaffold-helpers';
import {
  SHADCN_VARS,
  ResolvedVisual,
  resolveVisual,
} from '../shared/brand-tokens';

export interface NextjsAppGeneratorSchema {
  name: string;
  auth: 'none' | 'clerk';
  apiProxy: boolean;
  websockets: boolean;
}

/** Render app/brand.css from the resolved visual tokens. globals.css imports
 *  this file and owns the structure (token mappings + surface utilities); this
 *  file is pure values and is regenerated, never hand-edited. */
function renderBrandCss(v: ResolvedVisual): string {
  const out: string[] = [];
  out.push('/* GENERATED by the GroundWork nextjs-app generator from');
  out.push(' * .groundwork/config/brand-tokens.json — do not hand-edit this file.');
  out.push(' * Re-run the design system to evolve the brand, then regenerate.');
  out.push(' * app/globals.css imports this file and maps these values into Tailwind');
  out.push(' * token utilities and surface classes; components consume those, never');
  out.push(` * these variables directly. Projection source: ${v.source}. */`);
  out.push('');
  out.push(':root {');
  out.push(`  --radius: ${v.radius};`);
  for (const name of Object.keys(SHADCN_VARS)) {
    out.push(`  --${name}: ${v.shadcn[name].light};`);
  }
  out.push('');
  out.push('  /* Atmosphere — blur radii, elevation stacks, hero gradient. */');
  out.push(`  --gw-blur-subtle: ${v.blur.subtle};`);
  out.push(`  --gw-blur-standard: ${v.blur.standard};`);
  out.push(`  --gw-blur-heavy: ${v.blur.heavy};`);
  out.push(`  --gw-shadow-low: ${v.shadow.low.light};`);
  out.push(`  --gw-shadow-mid: ${v.shadow.mid.light};`);
  out.push(`  --gw-shadow-high: ${v.shadow.high.light};`);
  out.push(`  --gw-gradient-hero: ${v.gradientHero.light};`);
  out.push('');
  out.push('  /* Surface treatments — tint + border per named treatment. */');
  for (const name of ['glass', 'elevated', 'hero'] as const) {
    out.push(`  --gw-surface-${name}-tint: ${v.surfaces[name].tint.light};`);
    out.push(`  --gw-surface-${name}-border: ${v.surfaces[name].border.light};`);
  }
  out.push('');
  out.push('  /* Typography roles — size, line-height, weight, tracking. */');
  for (const [role, r] of Object.entries(v.typeRoles)) {
    out.push(`  --gw-text-${role}-size: ${r.size};`);
    out.push(`  --gw-text-${role}-line: ${r.line};`);
    out.push(`  --gw-text-${role}-weight: ${r.weight};`);
    out.push(`  --gw-text-${role}-tracking: ${r.tracking};`);
  }
  out.push('');
  out.push('  /* Motion interaction profiles — duration, easing, transform. */');
  for (const [ctx, m] of Object.entries(v.motion)) {
    out.push(`  --gw-motion-${ctx}-duration: ${m.duration};`);
    out.push(`  --gw-motion-${ctx}-ease: ${m.ease};`);
    out.push(`  --gw-motion-${ctx}-transform: ${m.transform};`);
  }
  out.push('}');
  out.push('');
  out.push('.dark {');
  for (const name of Object.keys(SHADCN_VARS)) {
    out.push(`  --${name}: ${v.shadcn[name].dark};`);
  }
  out.push('');
  out.push('  /* Atmosphere — dark-theme variants. */');
  out.push(`  --gw-shadow-low: ${v.shadow.low.dark};`);
  out.push(`  --gw-shadow-mid: ${v.shadow.mid.dark};`);
  out.push(`  --gw-shadow-high: ${v.shadow.high.dark};`);
  out.push(`  --gw-gradient-hero: ${v.gradientHero.dark};`);
  for (const name of ['glass', 'elevated', 'hero'] as const) {
    out.push(`  --gw-surface-${name}-tint: ${v.surfaces[name].tint.dark};`);
    out.push(`  --gw-surface-${name}-border: ${v.surfaces[name].border.dark};`);
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}

export default async function (tree: Tree, options: NextjsAppGeneratorSchema) {
  const serviceNames = names(options.name);
  const projectRoot = `services/${serviceNames.fileName}`;

  // Calculate assignedPort from docker-compose.yml (base 4000, sequential)
  let assignedPort = 4000;
  let composeDoc: any = null;
  if (tree.exists('docker-compose.yml')) {
    try {
      const yaml = require('yaml');
      const composeContent = tree.read('docker-compose.yml', 'utf-8');
      composeDoc = yaml.parseDocument(composeContent);

      const usedPorts = new Set<number>();

      // Collect ports from docker-compose.yml
      const servicesMap = composeDoc.get('services');
      if (servicesMap && servicesMap.items) {
        for (const item of servicesMap.items) {
          const service = item.value;
          if (service && service.get) {
            const ports = service.get('ports');
            if (ports && ports.items) {
              for (const pItem of ports.items) {
                const portStr = String(pItem.value || pItem);
                const match = portStr.match(/^(\d+):/);
                if (match) {
                  usedPorts.add(parseInt(match[1], 10));
                }
              }
            }
          }
        }
      }

      // Also collect ports from .env files of natively-run services (not in docker-compose)
      if (tree.exists('services')) {
        for (const svcName of tree.children('services') ?? []) {
          const envPath = `services/${svcName}/.env`;
          if (tree.exists(envPath)) {
            const envContent = tree.read(envPath, 'utf-8') ?? '';
            for (const line of envContent.split('\n')) {
              const m = line.match(/^(?:PORT|SERVER_PORT)=(\d+)/);
              if (m) usedPorts.add(parseInt(m[1], 10));
            }
          }
        }
      }

      while (usedPorts.has(assignedPort)) {
        assignedPort++;
      }
    } catch (e) {
      console.warn('Failed to parse docker-compose.yml for port calculation:', e);
    }
  }

  const templateOptions = {
    ...options,
    ...serviceNames,
    assignedPort,
    tmpl: '' // required by generateFiles
  };

  generateFiles(
    tree,
    path.join(__dirname, '..', '..', '..', '..', 'src', 'generators', 'nextjs-app', 'files'),
    projectRoot,
    templateOptions
  );

  deployStackDocs(tree, path.join(__dirname, '..', '..', '..', '..', 'src', 'generators', 'nextjs-app', 'docs'));

  // Nx's generateFiles treats __var__ as template substitution, which
  // conflicts with Next.js dynamic route segments like [...path] and
  // [[...sign-in]]. We use placeholder dir names and rename post-generation.
  const renames: [string, string][] = [
    [`${projectRoot}/app/api/proxy/__path__`, `${projectRoot}/app/api/proxy/[...path]`],
    [`${projectRoot}/app/(auth)/sign-in/__sign-in__`, `${projectRoot}/app/(auth)/sign-in/[[...sign-in]]`],
    [`${projectRoot}/app/(auth)/sign-up/__sign-up__`, `${projectRoot}/app/(auth)/sign-up/[[...sign-up]]`],
  ];

  for (const [oldDir, newDir] of renames) {
    // Find all files under the old directory and move them
    const children = tree.children(oldDir);
    if (children && children.length > 0) {
      for (const child of children) {
        const content = tree.read(`${oldDir}/${child}`);
        if (content) {
          tree.write(`${newDir}/${child}`, content);
          tree.delete(`${oldDir}/${child}`);
        }
      }
    }
  }

  // Project brand-tokens.json's visual block into app/brand.css — the per-app
  // palette + atmosphere layer (elevation, blur, gradients, surface treatments,
  // type-role micro, motion profiles). Parity with electron-app/flutter-app:
  // globals.css imports this file and owns the structure, this file owns the
  // values, and no engineer skill carries a fixed aesthetic catalogue.
  tree.write(
    `${projectRoot}/app/brand.css`,
    renderBrandCss(resolveVisual(tree)),
  );

  // Auto-inject into docker-compose.yml if it exists
  if (composeDoc) {
    try {
      if (!composeDoc.get('services')) {
        // createNode so the result is a YAMLMap with .has/.set (a plain {} is not).
        composeDoc.set('services', composeDoc.createNode({}));
      }
      const servicesMap = composeDoc.get('services');
      if (!servicesMap.has(serviceNames.fileName)) {
        const envVars = [
          `PORT=${assignedPort}`,
          `OTEL_SERVICE_NAME=${serviceNames.fileName}`,
          'OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318',
        ];

        if (options.apiProxy) {
          envVars.push('API_URL=http://core:4000');
        }

        if (options.auth === 'clerk') {
          envVars.push('NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}');
          envVars.push('CLERK_SECRET_KEY=${CLERK_SECRET_KEY}');
        }

        const newService: Record<string, unknown> = {
          build: {
            context: `./${projectRoot}`,
            dockerfile: 'Dockerfile'
          },
          container_name: serviceNames.fileName,
          restart: 'unless-stopped',
          ports: [
            `${assignedPort}:${assignedPort}`
          ],
          environment: envVars,
          // The node:alpine runtime image has no curl, but ships busybox wget,
          // which probes the health route without an extra binary.
          healthcheck: {
            test: [
              'CMD',
              'wget',
              '-q',
              '--spider',
              `http://localhost:${assignedPort}/api/healthz`
            ],
            interval: '10s',
            timeout: '5s',
            retries: 5,
            start_period: '20s'
          },
          networks: [
            'groundwork-net'
          ]
        };

        servicesMap.set(serviceNames.fileName, newService);
        // A Next.js app exports OTLP telemetry but uses no database, so it
        // provisions jaeger only (no longer in the base compose).
        ensureOptionalInfra(composeDoc, servicesMap, {
          usesRedis: false,
          usesPubSub: false,
          usesTelemetry: true,
          projectPrefix: readProjectPrefix(tree),
        });
        tree.write('docker-compose.yml', composeDoc.toString());
      }
    } catch (e) {
      console.warn('Failed to update docker-compose.yml:', e);
    }
  }

  // Conditionally remove auth files
  if (options.auth !== 'clerk') {
    tree.delete(`${projectRoot}/app/(auth)`);
    tree.delete(`${projectRoot}/proxy.ts`);
    tree.delete(`${projectRoot}/proxy.test.ts`);
    tree.delete(`${projectRoot}/components/providers/production.tsx`);
  }

  // Conditionally remove API proxy files
  if (!options.apiProxy) {
    tree.delete(`${projectRoot}/app/api/proxy`);
    tree.delete(`${projectRoot}/lib/api`);
    tree.delete(`${projectRoot}/lib/config.ts`);
  }

  // Conditionally remove websocket files
  if (!options.websockets) {
    tree.delete(`${projectRoot}/app/api/config`);
  }

  promoteEngineerSkill(tree, 'groundwork-nextjs-engineer');

  await formatFiles(tree);

  recordGeneratorProvenance(tree, 'nextjs-app', options as unknown as Record<string, unknown>);

  return () => {
    const { execSync } = require('child_process');
    try {
      execSync('pnpm install', { cwd: projectRoot, stdio: 'inherit' });
    } catch (e) {
      console.warn(`Failed to run pnpm install in ${projectRoot}. Run it manually.`);
    }
  };
}
