// Validates a legacy content directory (default: the Word Loop fixture). JSON Schemas are generated by schemas.ts.
import path from 'node:path'
import { loadContent } from '../src/data/content.ts'
import { livePrototypeIds } from '../src/data/live-prototypes.ts'
import { readContentDirectory } from '../server/content-files.ts'
const root = path.resolve(import.meta.dirname, '..')
try {
  const snapshot = loadContent(await readContentDirectory(path.resolve(process.argv[2] ?? path.join(root, 'tests/fixtures/wordloop/content'))), livePrototypeIds)
  console.log(`Valid content: ${snapshot.workspaces.length} workspaces, ${snapshot.products.length} products, ${snapshot.components.length} components, ${snapshot.features.length} features.`)
} catch (error) { console.error(error instanceof Error ? error.message : error); process.exitCode = 1 }
